### ISSUE TITLE
Cannot find module "child_process"

### ISSUE THREAD

**Issue by jemomi** [shopgun/shopgun-js-sdk#33]
Getting this error after updating to 2.1.4:
bundle.js:28802 Uncaught Error: Cannot find module "child_process"
at webpackMissingModule (bundle.js:28802)
at bundle.js:28802
at Object.<anonymous> (bundle.js:28805)
at Object.<anonymous> (bundle.js:40988)
at _webpack_require_ (bootstrap 938a2135e317cbe97e17:19)
at Object.<anonymous> (es7.string.pad-end.js:8)
at _webpack_require_ (bootstrap 938a2135e317cbe97e17:19)
at Object.defineProperty.value (es7.string.match-all.js:6)
at _webpack_require_ (bootstrap 938a2135e317cbe97e17:19)
at Object.<anonymous> (es7.reflect.get-own-metadata-keys.js:4)

![2018-03-23_1231](https://user-images.githubusercontent.com/4638240/37894631-170f5bca-30df-11e8-8268-555984380ff1.png)

**Comment by mortenbo** [comment]
Thanks for the bug report. We also noticed this last week in a require.js environment. We'll have a fix up today. Will advise.

**Comment by mortenbo** [comment]
@jemomi `2.1.5` is out with a fix now :) Sorry for the inconvenience.

**Comment by mortenbo** [comment]
@jemomi Let's try again with `2.1.6`. We identified another issue with using webpack.
